-- Add regular season per-game stats to players table
ALTER TABLE players ADD COLUMN IF NOT EXISTS season_ppg REAL DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS season_rpg REAL DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS season_apg REAL DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS season_spg REAL DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS season_bpg REAL DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS season_mpg REAL DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS season_gp  INTEGER DEFAULT 0;
